version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/blog
      ROCKET_ADDRESS: 0.0.0.0
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
