# Définir cette configuration Compose afin de lancer l'application
# Grilli en production.
version: '3.8'

services:
  grilli_app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./public:/var/www/public
    environment:
      APP_ENV: prod
    networks:
      - grilli_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      #- ./public:/var/www/public:ro
      #- ./docker/nginx/grilli.com.conf:/etc/nginx/conf.d/default.conf:ro
      - ./path/to/your/nginx/conf/grilli.com.conf:/etc/nginx/conf.d/default.conf:ro

    depends_on:
      - grilli_app
    networks:
      - grilli_network

networks:
  grilli_network:
    driver: bridge

