# Définir cette configuration Compose afin de lancer l'application
# Grilli en production.
version: '3.8'

services:
  grilli_app:
    hostname: php
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - php:/var/www/html

    environment:
      - APP_ENV=${APP_ENV}

  nginx:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./.docker/nginx/grilli.com.conf:/etc/nginx/conf.d/default.conf:ro
      - php:/var/www/html

    depends_on:
      - grilli_app

volumes:
  php:
