# Définir cette configuration Compose afin de lancer l'application
# Make Me Watch en production.

version: '3.8'

services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5000:5173"
    env_file:
      - ./client/.env
    networks:
      - tvshows_net
      
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - tvshows_net
    

networks:
  tvshows_net:
    name: tvshows_net
